# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72535d005fe212bf0aa9b50a9fbe9e057da0680785c47784eb28add231e581aac0640c45b412dbbdaa156f3616cf84ff20a83b466f2f4a0915371856c88d722c

test:
  secret_key_base: c93276a6765abb4827abcaf6b1263cae51f63fbeb4e823f5fd3777bbb8c2bc272e7f3802542469c1365cb31d89836f2bd37464f3afb20aea53a097dd052941fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
